apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    openshift.io/display-name: Terminal
  name: terminal-base-openshift-auth
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.first: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"${APPLICATION_NAME}"}}'
      serviceaccounts.openshift.io/oauth-redirecturi.first: hub/oauth_callback
      serviceaccounts.openshift.io/oauth-want-challenges: "false"
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-hub
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${APPLICATION_NAME}-hub
- apiVersion: v1
  kind: ImageStream
  lookupPolicy:
    local: true
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-hub-s2i
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-hub-s2i
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}-hub-s2i:latest
    source:
      git:
        ref: 1.0.4
        uri: https://github.com/jupyter-on-openshift/jupyterhub-quickstart.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: ImageStream
  lookupPolicy:
    local: true
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-hub-img
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-hub-img
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}-hub-img:latest
    source:
      git:
        ref: 1.0.0
        uri: https://github.com/openshift-evangelists/training-openshift-auth.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}-hub-s2i:latest
      type: Source
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: APPLICATION_NAME
            value: ${APPLICATION_NAME}
          - name: USER_IMAGE_NAME
            value: ${APPLICATION_NAME}-app-base
          - name: DEFAULT_PAGE
            value: terminal
          - name: MEMORY_SIZE
            value: ${MEMORY_SIZE}
          - name: VOLUME_SIZE
            value: ${VOLUME_SIZE}
          - name: ADMIN_USERS
            value: ${ADMIN_USERS}
          - name: IDLE_TIMEOUT
            value: ${IDLE_TIMEOUT}
          image: ${APPLICATION_NAME}-hub-img:latest
          name: spawner
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
          - mountPath: /opt/app-root/data
            name: data
        serviceAccountName: ${APPLICATION_NAME}-hub
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ${APPLICATION_NAME}-hub-data
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spawner
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}-hub-img:latest
      type: ImageChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APPLICATION_NAME}-hub-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ""
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
- apiVersion: v1
  kind: ImageStream
  lookupPolicy:
    local: true
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-app-base
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-app-base
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}-app-base:latest
    source:
      git:
        ref: 1.0.0
        uri: https://github.com/openshift-evangelists/workshop-base-image.git
      type: Git
    strategy:
      dockerStrategy:
        buildArgs:
        - name: OC_VERSION
          value: ${OC_VERSION}
        - name: ODO_VERSION
          value: ${ODO_VERSION}
        - name: KUBECTL_VERSION
          value: ${KUBECTL_VERSION}
        from:
          kind: DockerImage
          name: centos/s2i-base-centos7:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
parameters:
- name: APPLICATION_NAME
  required: true
  value: terminal
- name: MEMORY_SIZE
  value: 512Mi
- name: VOLUME_SIZE
  value: 1Gi
- name: ADMIN_USERS
- name: IDLE_TIMEOUT
  value: "7200"
- name: OC_VERSION
  required: true
  value: 3.10.41
- name: ODO_VERSION
  required: true
  value: 0.0.12
- name: KUBECTL_VERSION
  required: true
  value: 1.10.0
