---
features_to_install: [etherpad, gogs, guides, nexus, ocp-ops-view, terminals]

# DEFAULTS
# namespace: ocp-workshop # This is defined in common-definitions
apps_hostname_suffix: apps.osevg.openshiftworkshop.com
openshift_master_url: https://master.osevg.openshiftworkshop.com
workshop_type: java
infrasvcs_adm_user: adminuser
infrasvcs_adm_password: admin123
openshift_user_password: openshift
# user_count: 0 # This is defined in common-definitions
# user_format: user%d # Theis is defined in common-definitions
nexus_release_version: 3.12.1
gogs_release_version: 0.11.34


reponame: "nationalparks"
install_custom_stacks_json: []

# per-user quotas
quota_pods: 30
quota_persistentvolumeclaims: 10
quota_services: 30
