---
#####
# Guides (Workshopper)
#####
- name: "Process guides template (for java workshop)"
  import_role:
    name: homeroom_labs_deployer
  vars:
    lab_repo: "{{ workshop_repo }}"
    lab_branch: "{{ workshop_branch }}"
    workshop_file: "java-workshop.yml"
  when: workshop_type == "java"

- name: "Process guides template (for python workshop)"
  import_role:
    name: homeroom_labs_deployer
  vars:
    lab_repo: "{{ workshop_repo }}"
    lab_branch: "{{ workshop_branch }}"
    workshop_file: "python-workshop.yml"
  when: workshop_type == "python"

- name: "Process guides template (for node.js workshop)"
  import_role:
    name: homeroom_labs_deployer
  vars:
    lab_repo: "{{ workshop_repo }}"
    lab_branch: "{{ workshop_branch }}"
    workshop_file: "javascript-workshop.yml"
  when: workshop_type == "node.js"

- name: "Process guides template (for php workshop)"
  import_role:
    name: homeroom_labs_deployer
  vars:
    lab_repo: "{{ workshop_repo }}"
    lab_branch: "{{ workshop_branch }}"
    workshop_file: "php-workshop.yml"
  when: workshop_type == "php"

#
# PHP specific 
#

- name: "Copy updated PHP+mongodb IS to temp"
  block:
    - copy:
        src: php-is.yml
        dest: "{{ tmp_dir.path }}/php-is.yml"
    - command: "oc replace -f php-is.yml -n openshift"
      args:
        chdir: "{{ tmp_dir.path }}"
  when: workshop_type == "php"
